### ISSUE TITLE
Basic Working example

### ISSUE THREAD

**Issue by alxblog** [fratzinger/feathers-casl#13]
Hi 👋,

First thing first, thank you for this awesome Casl integration initiative. 
I followed your "Getting Started", but it does not work. 
hooks in _**authentication.hooks.js**_ file seem never called, maybe because _authentication_ service (and hooks) is not registered in **authentication.js** generated file. 
Do you have any basic working example repository ? 

Thank you and have a nice day !

**Comment by fratzinger** [comment]
hey,
I've got no working example. Which version of feathers do you use? Is it generated by `@feathersjs/cli` or how do you organize it? If you like, share your `authentication.js` or just some parts.

**Comment by alxblog** [comment]
Thank you for your reply (it's my first issue request on Github). 
I use Feathers 4.5.11, I tried to set Feathers-casl up on a stock and fresh CLI generated app (with NeDB). 

So the basic **authentication.js** file is 
```js
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');
const { LocalStrategy } = require('@feathersjs/authentication-local');
const { expressOauth } = require('@feathersjs/authentication-oauth');

module.exports = app => {
  const authentication = new AuthenticationService(app);

  authentication.register('jwt', new JWTStrategy());
  authentication.register('local', new LocalStrategy());

  app.use('/authentication', authentication);
  app.configure(expressOauth());
};
```

If, in the same file, I register "authentication" service and hooks that lets trig **authentication.hooks.js**

```js
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');
const { LocalStrategy } = require('@feathersjs/authentication-local');
const { expressOauth } = require('@feathersjs/authentication-oauth');
const hooks = require('./services/authentication/authentication.hooks'); // require authentication.hooks

module.exports = app => {
  const authentication = new AuthenticationService(app);

  authentication.register('jwt', new JWTStrategy());
  authentication.register('local', new LocalStrategy());

  app.use('/authentication', authentication);
  app.service('authentication').hooks(hooks); //register authentication service and hooks
  app.configure(expressOauth());
};
```

is that the good way to do it ?

**Comment by fratzinger** [comment]
Yep, that's definitely a way. 
You should have at least a folder with `src/services/users` containing `users.service.js` and `users.hooks.js`. Since the authentication is just another service (like all the other services), I handle it the exact same way.
Your `authentication.js` file is pretty much the same as `users.service.js`, so I renamed the `authentication.js` file in `authentication.service.js` and followed the same way as in `users.service.js` to register the hooks.

After this setup your `after:create` hook in `authentication.hooks.js` does not get called? If so, what does your `authentication.hooks.js` look like?

**Comment by alxblog** [comment]
So, I renamed (just to follow your logic) **_./src/authentication.js_** in _**authentication.service.js**_ and move it to **_./src/services/authentication/_** 
Authentication service hooks are now called. _ability_ and _rules_ props are present in POST authentication response.

_authentication.abilities.js_ and authentication.hooks.js are exactly de same as your example (copy/past) in your "Getting Started" section. 

the only last thing I did is to add authorize() hook to **tasks.hooks.js**

```js
const { authenticate } = require('@feathersjs/authentication').hooks;
const { authorize } = require('feathers-casl').hooks;

module.exports = {
  before: {
    all: [authenticate('jwt')],
    find: [
      authorize({ checkAbilityForInternal: true }) // make sure this hook runs always last
    ],
    get: [
      authorize({ checkAbilityForInternal: true }) // make sure this hook runs always last
    ],
    create: [
      authorize({ checkAbilityForInternal: true }) // make sure this hook runs always last
    ],
    update: [
      authorize({ checkAbilityForInternal: true }) // make sure this hook runs always last
    ],
    patch: [
      authorize({ checkAbilityForInternal: true }) // make sure this hook runs always last
    ],
    remove: [
      authorize({ checkAbilityForInternal: true }) // make sure this hook runs always last
    ]
  },

  after: {
    all: [
      authorize({ checkAbilityForInternal: true }), // make sure this hook runs always first
    ],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```

**Comment by fratzinger** [comment]
So is there anything left?^^

**Comment by fratzinger** [comment]
If not, you could close the issue then. I won't add an example for now, but will keep it in my mind for later.

Do you know of the feathers slack group? It's a better place for general questions. http://slack.feathersjs.com/ :)

**Comment by alxblog** [comment]
Maybe it's a misunderstanding  of CASL, but if I do a GET/READ (find) request on **_tasks_** service, I still have all tasks. not only tasks owned by the current authenticated user (use id : 75RYYlBKLp2HyAeF) . 

```JSON
{
    "total": 2,
    "limit": 10,
    "skip": 0,
    "data": [
        {
            "text": "my task 4",
            "userId": "75RYYlBKLp2HyAeF",
            "_id": "3ZLQN4eiLCQzsPjk"
        },
        {
            "text": "my task 4",
            "userId": "foobar",
            "_id": "fwracLtabKpi2GX2"
        }
    ]
}

``` 

Should it not be "filtered" by 
```JS
can('manage', 'tasks', { userId: user.id });
```

PS: Thank you for the feathers slack channel.

**Comment by fratzinger** [comment]
Please post all your rules and what is the output of `console.log(user.id)`?
In a hook right before the `authorize()`-hook, what is the output of `console.log(context.params.user)`?

**Comment by alxblog** [comment]
Here is the authentication.abilites.js 

```js
const { AbilityBuilder, createAliasResolver, makeAbilityFromRules } = require('feathers-casl');

// don't forget this, as `read` is used internally
const resolveAction = createAliasResolver({
	update: 'patch',       // define the same rules for update & patch
	read: ['get', 'find'], // use 'read' as a equivalent for 'get' & 'find'
	delete: 'remove'       // use 'delete' or 'remove'
});

const defineRulesFor = (user) => {
	// also see https://casl.js.org/v5/en/guide/define-rules
	const { can, cannot, rules } = new AbilityBuilder();

	console.log(user.id) //debug purpose

	if (user.role && user.role.name === 'SuperAdmin') {
		// SuperAdmin can do evil
		can('manage', 'all');
		return rules;
	}

	if (user.role && user.role.name === 'Admin') {
		can('create', 'users');
	}

	can('read', 'users');
	can('update', 'users', { id: user.id });
	cannot('update', 'users', ['roleId'], { id: user.id });
	cannot('delete', 'users', { id: user.id });

	can('manage', 'tasks', { userId: user.id });
	can('create-multi', 'posts', { userId: user.id })

	return rules;
};

const defineAbilitiesFor = (user) => {
	const rules = defineRulesFor(user);

	return makeAbilityFromRules(rules, { resolveAction });
};

module.exports = {
	defineRulesFor,
	defineAbilitiesFor
};
```

`console.log(user.id)` returned `undefined`

and in tasks.hooks.js 

```js
const { authenticate } = require('@feathersjs/authentication').hooks;
const { authorize } = require('feathers-casl').hooks;

module.exports = {
  before: {
    all: [authenticate('jwt')],
    find: [
      (context) => {
        console.log(context.params.user) //debug purpose
        console.log(context.params.ability) //debug purpose
      },
      authorize({
        checkAbilityForInternal: true,
      }) // make sure this hook runs always last
    ],
//[...]
```

`context.params.user` returned  
```js
{
  email: 'foobar@email.com',
  password: '$2a$10$tTeAjaao60c0f7n1zIrlOubu6pNpRnckYFI37drSOmjYebVmfkrte',
  firstname: 'Alex',
  lastname: 'Auss',
  active: true,
  _id: '75RYYlBKLp2HyAeF'
}
```

and `context.params.user` returned   `undefined`


I just publish a repo with my files : 
https://github.com/alxblog/feathers-casl-example

**Comment by fratzinger** [comment]
multiple problems here:
1. you use `_id`, not `id`
2. if `context.params.ability` is undefined, so `authorize()` will be skipped at all
Please set some breakpoints here and there and see how it goes. First of all check the hook in `authentication.hooks.js`, then your `authentication.abilities.js`.

**Comment by fratzinger** [comment]
did you find the error? What was the problem?
If there's anything left, let me know.

**Comment by dasantonym** [comment]
Alright, thanks for clarifying, I hadn't looked at the Vue integration yet at all. Very nice!
