### ISSUE TITLE
Potential security issue for authorize hook?

### ISSUE THREAD

**Issue by jesslekova** [fratzinger/feathers-casl#14]
Hi, I'm new to feathers-casl and was playing around with it today.  I might have found a potential security issue for the authorize hook but I'm not 100% sure.  Please see the following setup and let me know if something's wrong.  Thanks!

This is the hook file for a service called 'test-tables'.  I made two blocks (BLOCK 1) and (BLOCK 2) and they are in before all hook and before create hook correspondingly.

```
before: {
    all: [
      authenticate('jwt'),
      // BLOCK 1
      context => {
        const user = context.params.user

        const defineRulesFor = () => { 
          const { can, rules } = new AbilityBuilder()
          if (user.role && user.role === 'everyone') {
            can('manage', 'all')
          }

          return rules
        }

        const rules = defineRulesFor()
        const ability = makeAbilityFromRules(rules, { resolveAction })
        context.params.ability = ability
      }
    ],
create: [
      // BLOCK 2
      authorize({
        ability: context => {
          const user = context.params.user

          const defineRulesFor = () => { 
            const { cannot, rules } = new AbilityBuilder()
            if (user.role && user.role === 'everyone') {
              cannot('create', 'testTables')
            }

            return rules
          }

          const rules = defineRulesFor()
          return makeAbilityFromRules(rules, { resolveAction })
        }
      })
    ]
}
```

The following were declared on top of the hook file

```
const { authorize } = require('feathers-casl').hooks
const { AbilityBuilder, createAliasResolver, makeAbilityFromRules } = require('feathers-casl')

const resolveAction = createAliasResolver({
  update: 'patch',       // define the same rules for update & patch
  read: ['get', 'find'], // use 'read' as a equivalent for 'get' & 'find'
  delete: 'remove'       // use 'delete' or 'remove'
})
```

Here are the behaviors that I discovered:

1. If I commented out BLOCK 1, the user would NOT be able to create an entry to test-tables (with error "error: Forbidden: You are not allowed to create test-tables").  This makes sense because of the cannot rules set in BLOCK 2.

2. And here comes the potential issue: if I have both BLOCK 1 and BLOCK 2, the request was able to create an entry in test-tables.  I would assume the authorize hook's ability option should have precedent over BLOCK 1 because anyone in the public can fake the same structure produced in BLOCK 1?

Thanks for your time.

**Comment by fratzinger** [comment]
Hey, thanks for your issue and your thoughts. What is the service path of "testTables"? Is it really "testTables" or is it "test-tables"?

**Comment by jesslekova** [comment]
Hi, I tried both and it seems to have the same behaviors.  But 'test-tables' is the service path.  Thanks!

**Comment by fratzinger** [comment]
Okay, if it has the same behavior for `cannot('create', 'test-tables')`, I will set up a scenario in the tests and will see what's going on there. If you got the time, you could do that as well. It's preconfigured to work with VSCode-breakpoints :)

Something worth noting: In my whole application, I just use one hook and predefine the rules in one single place (in the after-hook of authentication. Then, after `authenticate(...)` the `ability` is in `context.params` automatically. That way this concern, that you have, is not there.

Anyway I will look into it. If you got something in the meantime, please let me know. Thanks for your report :)

**Comment by fratzinger** [comment]
Hey @jesslekova,
sorry for the delay. I hope finally I got something for that problem. Please run `npm install feathers-casl@0.4.1-6` and see if that helps.

Please let me know how it went! :)

**Comment by fratzinger** [comment]
Closed because of inactivity. If there's something else, please let me know.
