### ISSUE TITLE
Examples from documentation not work with TS 

### ISSUE THREAD

**Issue by VladimirMalkov** [fratzinger/feathers-casl#26]
[This code example](https://feathers-casl.netlify.app/getting-started.html#define-static-rules)
Issue with type annotations for `makeAbilityFromRules` function.
Please fix it or replace with `new Ability(rules, { resolveAction })`. I think it is especially important that all examples can be quickly launched with TS (TS documentation will be greatest solution).

**Comment by fratzinger** [comment]
Could you help fixing it?

**Comment by VladimirMalkov** [comment]
> Could you help fixing it?

Yes, will do it today!

**Comment by fratzinger** [comment]
Nice, thanks! Any contributions are highly appreciated! Looking forward for an PR.
If there's anything I can help with, let me know!

By the way, which version of `casl` do you use?

**Comment by fratzinger** [comment]
Hey @VladimirMalkov ,
please check out `npm i feathers-casl@0.4.1-8` from #20 . It should be fixed over there.

**Comment by fratzinger** [comment]
released as [v0.5.0](https://github.com/fratzinger/feathers-casl/releases/tag/v0.5.0)

**Comment by MalkovVladimir** [comment]
> released as [v0.5.0](https://github.com/fratzinger/feathers-casl/releases/tag/v0.5.0)

we did it same time) I decided to add ts to doc, but you change vue press to vite press ahah
Here it is https://github.com/fratzinger/feathers-casl/pull/27

To be honest, I cant move it to vitepress)

**Comment by fratzinger** [comment]
😆 Isn't there a vitepress equivalent?

**Comment by MalkovVladimir** [comment]
Will try to move tabs (js/ts) vis markdown-it plugin. It has tabs component.

**Comment by fratzinger** [comment]
Nice. Thank you very much for the work! I'll merge it then. Let me know if I can help! :)

**Comment by MalkovVladimir** [comment]
@fratzinger I think `style.styl` not affect on css) Cant find what exactly gone wrong...

**Comment by fratzinger** [comment]
Thanks for the notice! I've noticed that the green color has changed. The variable-names could have changed for vitepress maybe, but that's not really an issue for me. Anyway, if you found something, please let me know :)
