### ISSUE TITLE
Unexpected auth rejection

### ISSUE THREAD

**Issue by EmileSpecs** [fratzinger/feathers-casl#29]
Hi

I'm having some issues with a rule that doesn't seem to work correctly or as expected.

I have rules that are populated for the logged in user via the DB. One of the rules is:
```
{
    action: 'edit',
    subject: 'parts',
    conditions: { approved: false }
}
```

What I'm expecting to happen is that the user should be able to edit (patch) the parts service is the `approved` field is set to false and fail if it is set to true. Do I understand this correctly?

Currently it fails no matter what `approved` is set to.
When I remove the condition however, the rule does work as expected.

Any help would be appreciated.

**Comment by fratzinger** [comment]
What looks your `resolveAction` option on the ability? What's your servicePath? Which `feathers-casl` version do you use?

Your understanding sounds right to me.

**Comment by EmileSpecs** [comment]
```
const resolveAction = createAliasResolver({
  write: 'create',            // use 'write' as a equivalent for 'create'
  edit: ['patch', 'update'],  // use 'edit' as a equivalent for 'patch'
  update: 'patch',            // define the same rules for update & patch
  read: ['get', 'find'],      // use 'read' as a equivalent for 'get' & 'find'
  delete: 'remove'            // use 'delete' or 'remove'
});
```

```// Initialize our service with any options it requires
  app.use('/parts', new PartService(options, app));

  // Get our initialized service so that we can register hooks
  const service = app.service('parts');
```

If any of the above was incorrect I'd assume the permissions wouldn't work at all, but it works fine when I don't set a condition.
So I'm a little stumped as to why this isn't working...

Just installed newest feathers-casl, problem persists.

**Comment by EmileSpecs** [comment]
Log of data sent to patch:
```
DATA before@parts/patch: {
  description: 'Test',
  approved: false,
  starred: false,
  archived: false,
  ...
```
Error: Forbidden: You are not allowed to patch parts

**Comment by fratzinger** [comment]
It does not check your data you send to patch, but your data, that is in the database. What's your data in the db?

**Comment by EmileSpecs** [comment]
I just realized that!

Yes, it checks what the value of `approved` is in the DB, not data sent to the patch.

So I misunderstood how it would work for create and patch.
Wonder what would happen with `create`, since with create there is no data in the DB yet...

So I guess what I'm trying to do will have to be done with some other business logic in a hook, not with permissions?

**Comment by fratzinger** [comment]
It works with `create` as you would expect it.
Let me think about the `patch`. I'll come up with ideas in the next days.

If you have figured something out, please let me know.

**Comment by EmileSpecs** [comment]
For `get` and `find` it's clear that the DB value are checked against conditions.

For `create` it also more obvious that the data sent will be checked.

But with `patch` it isn't quite clear. It would be great if the conditions for patch could be targeted to a specific source: sent data or DB data.
I don't know how that could be done but perhaps you have some ideas...

Thanks for looking into this!

**Comment by fratzinger** [comment]
`update` would be the same as `patch`. For `patch` it starts to get complex for multi patches with `id: null`. You provide a `query` then, to tell which items should get updated. For that scenario, it's definitely more intuitive, that you check the query.

Your writing sounds like two separate hooks, like one with option `checkPatchData` with `true` and one with `false`. That's fairly easy, but not the most elegant way.
One way would be to define actions like: `can('patch-data', 'parts', { approved: false })`. That way you can have these new rules along with the existing ones.

**Comment by EmileSpecs** [comment]
I agree, that does seem like the more elegant solution, and also ties in with the way multi rules are defined: 
`can('create-multi', 'posts', { userId: user.id })`

How much work do you think this would be to get working?

**Comment by fratzinger** [comment]
Currently I've not that much time. The basics are fairly easy but I guess there are more things to come. For example: you define a 'patch-data' rule with conditions. What happens if the data doesn't have the properties from conditions at all? Skip? Throw? Ignore it? That would be an option you maybe want to define per rule.

Would is your opinion on that? What would you expect to happen?

Any contributions are highly appreciated. If you feel comfortable enough, please do a fork and see how far you get and make a PR.

**Comment by J3m5** [comment]
> What happens if the data doesn't have the properties from conditions at all? Skip? Throw? Ignore it? That would be an option you maybe want to define per rule.

That's interesting, another option could be to overwrite properties, like for example relations defining owners etc 
We currently do this in another backend, instead of checking a property we add/replace a secure default value tied to the user permissions, roles or organization.

**Comment by fratzinger** [comment]
Oh boy. Good point but doesn't make it easier 😆 Where would you expect defaults?
`feathers-casl` is about permissions, not `validation` or `defaults` which are often mistaken. Even the `patch-data` thing is more of a `validation`. There's [feathers-validate-joi](https://www.npmjs.com/package/feathers-validate-joi) for that, where you also can define defaults.
If we would add defaults to `feathers-casl` then I see it drifting away from `casl`.

I also have the defaults pattern based on the user making the request, but I handle it in another hook. [withData](https://daddywarbucks.github.io/feathers-fletching/hooks.html#withdata) is a nice way to solve that.

@J3m5: Are you allowed to share a bit of that code with the defaults (even pseudocode)? Is it tied to the `ability` of `casl` or is it a separate logic?

All the edge cases that can occur with these options (`patch-data`, `defaults`) could be hard to handle/understand/scale. There must be a way to define all these things in one library (`feathers-casl`, `feathers-validate-joi`, `@feathers/schema`, ...). Adding more and more models to the app (sql, typescript, json, ...) can't be an option.
I need a few hours to think about that 😄

**Comment by EmileSpecs** [comment]
I agree that this should stay within the permission realm, and that defaults or changing of values is not the job of a permissions system.

If the property of the condition is not contained in the data then permission is granted, since the condition cannot be violated if the property it is checking is not present.

Thus, I think this should stay fairly simple at first anyway, it can be further enhanced down the road if the need arises.
And with simple I mean that the rule should simply check the data object as apposed to the DB result object when `patch-data` is used.

**Comment by J3m5** [comment]
> Are you allowed to share a bit of that code with the defaults (even pseudocode)? Is it tied to the ability of casl or is it a separate logic?
This is a php code, not mine and it's really basic, just set this prop with this value and that's it.

> feathers-casl is about permissions, not validation or defaults which are often mistaken.

I agree, this is more about validation than permission.
I think feathers-casl should only check if the user has the right to patch or update by checking the data that is in the DB and the query for the multi patch.

**Comment by fratzinger** [comment]
I've started this (please checkout: https://github.com/fratzinger/feathers-casl/commit/a81f215802e7c0a9da70382718da7e288a6978b7)
@EmileSpecs: For a first glance, please checkout this with: `npm install feathers-casl@0.5.1-2`

**Comment by EmileSpecs** [comment]
Awesome!

Can't get it to work as expected however... Am I missing something here?

```
ability [
  ...
  { action: 'patch', subject: 'parts' },
  {
    action: 'patch-data',
    subject: 'parts',
    reason: 'You may not approve parts',
    inverted: true,
    conditions: { approved: true }
  }
]
```

Ability array above and then I send patch data that includes `{approved: true}` but then don't get an error?

**Comment by fratzinger** [comment]
Tests were false positive, sorry.
Please check out: `npm i feathers-casl@0.5.1-3`. It should work as expected now.

**Comment by EmileSpecs** [comment]
@fratzinger great, thanks, it works as expected now!

Would it be incorrect to assume that this should work in the client as well? I'm using Vue with Feathers Vuex.

Using `$can('patch-data', part.clone({approved: true}))` to test whether a user is allowed to approve a part does not work as it does in the API. The above should return `false` and if `{approved: false}` is should return `true`, both return false.

**Comment by fratzinger** [comment]
It didn't work on the client because you haven't a basic `can('patch-data', 'parts')` rule.

Please checkout `npm install feathers-casl@0.5.1-8`. You gotta change two things to make it work on the server and on the client:
1. Server side: on your `authorize`-hook pass the option: `usePatchData: true` as in:
```
all: [
  authorize({
    adapterName: 'feathers-mongoose',
    ability: ...
    usePatchData: true
  })
]
```
2. add a rule to your abilities:
```
ability [
  ...
  { action: 'patch', subject: 'parts' },
  { action: 'patch-data', subject: 'parts' },
  {
    action: 'patch-data',
    subject: 'parts',
    reason: 'You may not approve parts',
    inverted: true,
    conditions: { approved: true }
  }
]
```

By doing this, it should work on the server as before and should work on the client the same way. 
Let me know how it goes. Then I can add this to the docs and ship it as `v0.6.0`

**Comment by fratzinger** [comment]
Hey @EmileSpecs, how's it going? Did you have time to look into `v0.5.1-8`?

**Comment by EmileSpecs** [comment]
Hi @fratzinger!

Apologies, went on with other parts and functionality of the app so put this to the side for a while.

Got around to testing this yesterday and it worked as expected, nice! I will update here should I encounter any problems, but so far so good!

Can you just briefly explain what exactly `usePatchData` does?
So if it's not set `patch-data` actions will be ignored?

Thanks again!

**Comment by fratzinger** [comment]
Don't worry :) Great to hear it's working.

**Explanation:**
> So if it's not set patch-data actions will be ignored?
That's true. The reason why `usePatchData` is the other way around. Here are two scenarios:
1. If you expect `patch-data` to work (which are just a few use cases I assume), the requesting user needs to have rules with `patch-data` to be permitted. If a user hasn't `patch-data` rules, you would expect a rejection.
2. If you don't need the `patch-data` pattern (in my applications, ATM), you would expect, that a user is permitted to `patch-data` without the `patch-data` rules, because you don't want to define these rules at all.

So if you `usePatchData: true` but don't define any rule with `patch-data` subject at all, no user can make a `patch` request anymore.

**Comment by EmileSpecs** [comment]
Hi @fratzinger 

Okay, so that is a little problematic. The permissions are dynamic (generated by die user).

So as I have it, you can add standard rules such as:
```
{
    "action": "patch",
    "subject": "sections"
}
```

But conditional rules for that subject are optional, such as:
```
{
  action: 'patch-data',
  subject: 'sections',
  reason: 'You may not approve sections',
  inverted: true,
  conditions: { approved: true }
}
```

So if I set `userPatchData: true` but no rules are set that use it, the `patch` rule also fails.

Would it not make sense to simply imply by the action name (`actions.includes('-data'))` that the patch data should be used in that case?

**Comment by EmileSpecs** [comment]
In the meantime, I've added my own property to rules that require a `patch-data` variant:
```
{
    "action": "patch",
    "subject": "sections",
    "useDataVariant": true
}
```
I then generate a rule based on that:
```
{
  "action": "patch-data",
  "subject": "sections"
}
```

It then seems to work as expected.

**Comment by Gleb-Gaiduk** [comment]
Help please: https://stackoverflow.com/questions/70584146/nest-js-authorization-with-casl-doesnt-work-as-expected

**Comment by fratzinger** [comment]
@Gleb-Gaiduk: This is not `feathers-casl` specific nor is it related to this issue, right? I cannot help with nest. Consider waiting patiently on stackoverflow or go to https://gitter.im/stalniy-casl/casl as stated on https://github.com/stalniy/casl#have-a-question
