### ISSUE TITLE
Channels don't work

### ISSUE THREAD

**Issue by EmileSpecs** [fratzinger/feathers-casl#36]
Hi @fratzinger 

Me again!

The channels configuration as shown here: https://feathers-casl.netlify.app/getting-started.html#add-casl-to-channels
does not seem to work out of the box.

I'm patching a model and not getting that change event in my client as I do when I leave it as the default:
`return app.channel('authenticated');`

In the context of the model change `getChannelsWithReadAbility(app, data, context, caslOptions)` returns an empty array.

Am I missing something? Should I do anything else to get the channels to work?

**Comment by fratzinger** [comment]
Do you have `get`/`read` rules for the client?

**Comment by EmileSpecs** [comment]
Hi @fratzinger!

I found the issue! I did not set `ability` on the `connection` param.

Setting that seems to have solved it for me.

Thanks!
