### ISSUE TITLE
remove: No record found for id

### ISSUE THREAD

**Issue by dbvcode** [fratzinger/feathers-casl#57]
The record does not get deleted.
I simply call remove and the initial query looks like this:
```
{
  _id: '61e950d8fd8d585d5f23530e'
}
```
Then `softDelete` and `authorize` add their stuff and the query ends up like:

```
{
  _id: '61e950d8fd8d585d5f23530e',
  deleted: { '$ne': true },
  '$and': [ { _id: '61e950d8fd8d585d5f23530e' } ]
}
```
The remove action fails with the error: `No record found for id '61e950d8fd8d585d5f23530e'`.
The record exists and is not deleted so it should be good for deletion.
Without the `authorize` hook it gets deleted.
I assume the redundant `$and` parameter in the query is the culprit.

My hooks look like this:
```
import { disablePagination, setNow, softDelete } from 'feathers-hooks-common';
import { authorize } from 'feathers-casl/dist';
import logContext from '../../hooks/log-context';

export default {
  before: {
    all: [authorize({ adapter: 'feathers-mongodb' }), softDelete({})],
    find: [disablePagination()],
    get: [],
    create: [setNow('createdAt')],
    update: [setNow('updatedAt')],
    patch: [setNow('updatedAt')],
    remove: [setNow('updatedAt')]
  },

  after: {
    all: [authorize({ adapter: 'feathers-mongodb' })],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```

The applied rule for the user doing the delete:
`can('manage', 'artisans', { _id: '61e950d8fd8d585d5f23530e' });`

**Comment by fratzinger** [comment]
which adapter? mongoose?

**Comment by fratzinger** [comment]
Does it throw within the `authorize` hook or at the adapter?

**Comment by dbvcode** [comment]
The adapter is `mongodb` and I do have `$and` whitelisted.
The message is `No record found for id '61e950d8fd8d585d5f23530e'`.
How can I tell if it throws from the authorize hook or the adapter?

**Comment by fratzinger** [comment]
Add a hook after the `authorize` hook and see, if it gets called. Something like:
```js
all: [authorize({ adapter: 'feathers-mongodb' }),
  context => console.log('hello'),
  softDelete({})
],
```
