### ISSUE TITLE
After hook throwing forbidden error for get only conditional rules

### ISSUE THREAD

**Issue by vigalo** [fratzinger/feathers-casl#6]
Hello : 

Thank you for this great tool!!. I'm migrating my older application that was working well with feathers and CASL from feathers v3 (js) to v4 with ts using feathers-casl.

The rules are saved in DB and all of them are working well but one which has get only permission with conditional clause. To reproduce the problem, If I statically define the rule  can('get', 'users', { id: user.id }) instead of 'read' because I don't want to allow find, the after kook throws forbidden error. As soon as I remove the after hook it works fine.

This is because the forOneEl function tests for 'read' and if not allowed returns undefined causing the forbidden error .
![image](https://user-images.githubusercontent.com/1778891/106714143-b868ba80-65fb-11eb-9023-54fb2db48443.png)

Thank you.

**Comment by fratzinger** [comment]
Hey, thanks for your feedback and your report.

Are you capable of doing a pull request for this issue?

**Comment by J3m5** [comment]
I don't get it, shouldn't you define an alias for "get" in that case ? @vigalo

**Comment by fratzinger** [comment]
@J3m5 did you define the 'read' alias?
I think @vigalo is right with this one. `feathers-casl` should work with the default methods out of the box. Defining an `read` alias just for `get` method when you don't want to allow `find` seems like a weird workaround.

`read` should only be sugar for people who want same behavior for `find` and `get` and don't want to define ["find", "get"] every time.

**Comment by J3m5** [comment]
Ah, ok I see now, thanks.

**Comment by vigalo** [comment]
@J3m5, I defined the `read` alias to ["find", "get"] and using it in other rules. As @fratzinger says, I can't re-define the alias to only `get` and I don't want to allow `find`.

@fratzinger, I can do a PR for this issue but not at this moment. As a workaround, I modified the rule to `read` and when the migration is done will do the PR.

Thanks

**Comment by fratzinger** [comment]
by the way @vigalo. Do you also use `casl` on the client side? And if so, which framework (angular, react, vue) do you use?

**Comment by vigalo** [comment]
yes @fratzinger, I use `casl` on the client side with angular.

**Comment by fratzinger** [comment]
Ah nice. Do you use the `authentication` -after-hook approach or "just" the hooks?
Since `feathers-casl` is at an early stage and I'm not using angular, I'm searching for someone who could add some hints here: https://feathers-casl.netlify.app/client-side.html#angular  for how to get started with `feathers-casl` and angular. Would you mind sharing some snippets with us, that we can add to the docs to help others? 
I would highly appreciate it 😄

**Comment by vigalo** [comment]
Yes, I use the `authentication` after hook to load the abilities to use server side and previously I use a `custom authentication` service to send the abilities to client side in JWT payload . 
If I can help, let me know. I'm really busy at the moment but when I finish this tasks I will be glad to help others.
Thanks

**Comment by fratzinger** [comment]
This should be fixed in version `^0.1.8-0`.
Please try it again with `npm i feathers-casl@0.1.8-0` and give feedback. It's a pre-release. but it's more stable than the current version. Hopefully I will bring this to `v1` soon.

Please also notice that this is major upgrade from casl@4 to casl@5. You might come across errors, which should be fixable by following this: https://github.com/stalniy/casl/releases/tag/%40casl%2Fangular%405.0.0

**Comment by vigalo** [comment]
Hello @fratzinger. I installed `^0.1.8-0` and it seems to work well. The only problem I had was with  `@casl/angular`, but it is not related with your library. There is a problem with `webpack` and `angular 11`  with `.mjs` and required a `postinstall` hook:  [https://github.com/stalniy/casl/issues/427#issuecomment-758026538](url). I'll do further tests and report here if necessary.
Thanks a lot with your support.

**Comment by fratzinger** [comment]
Such mixed feelings 😄 Let me know, if I can do something about it. Unfortunately I know nothing about `angular` nor `.mjs` files.
Should this be a note in the docs? Is this an issue all `angular` users will come across?

**Comment by fratzinger** [comment]
released as stable with `^0.2.0`. See release notes: https://github.com/fratzinger/feathers-casl/releases/tag/v0.2.0
