### ISSUE TITLE
Missing resource results in "You are not allowed to get X" message

### ISSUE THREAD

**Issue by dasantonym** [fratzinger/feathers-casl#62]
### Steps to reproduce

Not sure if I am using this wrong:

- Try GETting a missing record

### Expected behavior

- Server returns 404

### Actual behavior

- Server says "You are not allowed to get X"

### System configuration

I have set up the hooks like this:

```javascript
module.exports = {
  before: {
    all: [
      authorize({ adapter: 'feathers-mongoose' })
    ]
  },
  after: {
    all: [
      authorize({ adapter: 'feathers-mongoose' })
    ]
  }
}
```

It seems to me that the `authorize` hook in `after` croaks and then produces this error, because I am depending on a field in the result to be checked. Could that be?

**Comment by dasantonym** [comment]
Can't really reproduce this anymore, closing!

**Comment by fratzinger** [comment]
Thanks for checking.
