### ISSUE TITLE
Documentation contains non-existent reference to @casl/ability -> makeAbilityFromRules

### ISSUE THREAD

**Issue by uplke** [fratzinger/feathers-casl#91]
### Steps to reproduce
[getting-started.md](https://github.com/fratzinger/feathers-casl/blob/main/docs/getting-started.md#define-static-rules)

### Expected doc
Since now using Ability() directly from CASL, makeAbilityFromRules is no longer a referenced export
```
import {
  Ability,
  AbilityBuilder,
  createAliasResolver
} from "@casl/ability";
```

### Actual doc
```
import {
  Ability,
  AbilityBuilder,
  createAliasResolver,
  makeAbilityFromRules
} from "@casl/ability";
```

_Thanks for this awesome project! - I have been looking forward to this update!_

**Comment by fratzinger** [comment]
Fixed, thanks for the issue. 💚

I would love to hear your use case for feathers-casl. If you feel like, please let me know for which product you use feathers-casl and maybe what's missing.

**Comment by uplke** [comment]
We have a digital marketing platform that serves mobile experiences to its users as they interact with digitally enabled lifestyle products.
A little background on the decision-making: we were looking for an un-opinionated API framework to more rapidly deploy new features and came across FeathersJS v4, which resonated with us due to similarities with some of our previous projects - it's simply straight-forward. Allowing to rely on enterprise-level industry standard packages was a big plus (Koa/Express, Passport, Joi, CASL). With Feathers v5, Joi became redundant, but authorization could still be spread through all service source files.
I have used CASL in an Enterprise application previously with excellent results and wanted to govern static role-based authorizations from a central location with the future option of moving to a dynamic permission model. For now, our use cases are simple and fully covered.
Thanks again to @fratzinger and @daffl for all the excellent work!

**Comment by fratzinger** [comment]
Great! Thanks for the insights. I highly appreciate it!
