### ISSUE TITLE
find rule with restricted field not working

### ISSUE THREAD

**Issue by romaincomtet** [fratzinger/feathers-casl#95]
### Bug Explanation and Fix Proposal
Steps to Reproduce
Use the following rule: can('read', 'users', ['id', 'pseudo']);
my authorize hook looks like
const authorizeHook = authorize({
  adapter: '@feathersjs/knex',
  availableFields: Object.keys(userSchema.properties),
});

### Expected Behavior
{
    "total": 2,
    "limit": 10,
    "skip": 0,
    "data": [
        {
            "id": "cefd6229-1e38-4dc4-8f18-0eae5abb8509",
            "pseudo": "mattp"
        },
        {
            "id": "490a4045-3c61-4878-a3d0-4984edc24354",
            "pseudo": "mattp"
        }
    ]
}

### Actual Behavior
{
    "total": 2,
    "limit": 10,
    "skip": 0,
    "data": [
        {}
    ]
}

### Error Source
The issue arises in the getItemsIsArray function called in authorizeAfter when the options parameter to { from: "result" } and the method is "find". In this scenario, the returned items value is incorrect.
### Actual
return in "items" = { "total": 2, "limit": 10, "skip": 0,"data": [[object],[object]]} and is array = false
### Expected
expected: should return when method  = "find" items = [[object],[object]] and is array = true

### Proposed Fix
two potential fixes:

#1
Change options = { from: "result" } to options = { from: "automatic" }.
#2
Add the following line to the getItemsIsArray function:
itemOrItems = itemOrItems && context.method === "find" ? itemOrItems.data || itemOrItems : itemOrItems;

Code Samples
Here are the relevant code snippets for the proposed fixes:

Fix 1:

const authorizeAfter = async (context, options) => {
  // ...
  let { isArray, items } = feathersUtils.getItemsIsArray(context, { from: "automatic" });
  // ...
};
Fix 2:
  const getItemsIsArray = (context, options) => {
    const {
      from = "automatic"
    } = options || {};
    let itemOrItems;
    if (from === "automatic") {
      itemOrItems = context.type === "before" ? context.data : context.result;
      itemOrItems = itemOrItems && context.method === "find" ? itemOrItems.data || itemOrItems : itemOrItems;
    } else if (from === "data") {
      itemOrItems = context.data;
    } else if (from === "result") {
      itemOrItems = context.result;
      itemOrItems = itemOrItems && context.method === "find" ? itemOrItems.data || itemOrItems : itemOrItems; // here
    }
    const isArray = Array.isArray(itemOrItems);
    return {
      items: isArray ? itemOrItems : itemOrItems != null ? [itemOrItems] : [],
      isArray
    };
  };

Module and Node.js Versions
Module versions: "^2.0.0"
Node.js version: v18.13.0

**Comment by fratzinger** [comment]
Thanks for the detailed bug report and sorry for the long delay!

Released as `v2.1.1` https://github.com/fratzinger/feathers-casl/releases/tag/v2.1.1 🎉
